### ISSUE TITLE
api.list_files(is_unassigned=True)

### ISSUE THREAD

**Issue by bsiranosian** [deeporiginbio/deeporigin-client#80]
From the tutorial: https://deeporiginbio.github.io/deeporigin-client/how-to/data-hub/list-data.html#list-files

```
TypeError: DeeporiginData.list_files() got an unexpected keyword argument 'is_unassigned'
```

version 2.1.4.

**Comment by bsiranosian** [comment]
Same thing with the example
```
api.list_files(assigned_row_ids=["row-1"])
```

In fact `list_files` function doesn't even appear in `api.py` ?

**Comment by sg-s** [comment]
hi ben, thanks for spotting that! yes, we overhauled our low-level API and the function signature changed. please use

```
api.list_files(filters=[dict(is_unassigned=True)])
```

i'll update the docs

**Comment by sg-s** [comment]
@bsiranosian the old behavior will come back in 

https://github.com/deeporiginbio/deeporigin-client/pull/81
